### ISSUE TITLE
[BUG] BroadcastTX returns  'pubKey does not match signer address'

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#389]
**Branch**: `mpc/fix-gas`
**Priority**: HIGH
**Stakeholders**: prnk28 mcjcloud

## Description

After signing and broadcasting a TX using the motor mpc wallet we are returned with an error that states the current public key does not match the Signer address of the TX.

```
code: 8
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'pubKey does not match signer address snr1qg94ysx8wjq63426m6889en4uau3hk40xl7krf52t8a8puf5nhtcks6khra
  with signer index: 0: invalid pubkey'
timestamp: ""
tx: null
txhash: 058FB07654DADF9DB91EB30ED600EFD5C541E26CE93FF7EFEEB27515085AC22B
```

## To Reproduce

1. Go to `internal/motor/motor_test.go`
2. Click Debug Test for `Test_CreateAccount`
3. See error

## Expected behavior

A successfully broadcasted transaction for the Registry Module.

## Simulation

When simulating the TX we are receiving a successful result.

```
did:snr:1qspxku3cu4987m3s2eqeqs4c63s7crxtxr2zkspp2tar57gqrdadvjq3tf8sj
data: CqoDCiQvc29ucmlvLnNvbnIucmVnaXN0cnkuTXNnQ3JlYXRlV2hvSXMSgQMS/gISQXNucjFxc3B4a3UzY3U0OTg3bTNzMmVxZXFzNGM2M3M3Y3J4dHhyMnprc3BwMnRhcjU3Z3FyZGFkdmpxM3RmOHNqGrACEkZkaWQ6c25yOjFxc3B4a3UzY3U0OTg3bTNzMmVxZXFzNGM2M3M3Y3J4dHhyMnprc3BwMnRhcjU3Z3FyZGFkdmpxM3RmOHNqKklkaWQ6c25yOjFxc3B4a3UzY3U0OTg3bTNzMmVxZXFzNGM2M3M3Y3J4dHhyMnprc3BwMnRhcjU3Z3FyZGFkdmpxM3RmOHNqI21lKk1kaWQ6c25yOjFxc3B4a3UzY3U0OTg3bTNzMmVxZXFzNGM2M3M3Y3J4dHhyMnprc3BwMnRhcjU3Z3FyZGFkdmpxM3RmOHNqI3NoYXJlZCpMZGlkOnNucjoxcXNweGt1M2N1NDk4N20zczJlcWVxczRjNjNzN2NyeHR4cjJ6a3NwcDJ0YXI1N2dxcmRhZHZqcTN0ZjhzaiN2YXVsdDCX4LiVBjgB
events:
- attributes:
  - index: false
    key: YWN0aW9u
    value: Y3JlYXRlX3dob19pcw==
  type: message
log: '[{"events":[{"type":"message","attributes":[{"key":"action","value":"create_who_is"}]}]}]'
```

## Additional Resources

* [Cosmos ADR-020: Proto TX Encoding](https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-020-protobuf-transaction-encoding.md)
* [Secp256k1 PubKey in Cosmos](https://pkg.go.dev/github.com/cosmos/cosmos-sdk@v0.45.5/crypto/keys/secp256k1?utm_source=gopls)
* [ECDSA Signing/Verification Reference](https://cryptobook.nakov.com/digital-signatures/ecdsa-sign-verify-messages)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534115577845) by [Unito](https://www.unito.io)
