### ISSUE TITLE
[SONR-11] Fix CI/CD Semver Bump

### ISSUE THREAD

**Issue by prdlk** [sonr-io/sonr#877]
Use goreleaser-pro in order to speed up and streamline the build process.

### Prepare Action

```
 release-build:
    strategy:
      matrix:
        GOOS: [linux, darwin]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true
      - shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" &gt;&gt; $GITHUB_ENV
      - id: cache
        uses: actions/cache@v3
        with:
          path: dist/${{ matrix.GOOS }}
          key: ${{ matrix.GOOS }}-${{ env.sha_short }}
      - uses: goreleaser/goreleaser-action@v4
        if: steps.cache.outputs.cache-hit != 'true' # do not run if cache hit
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean --split ${{ env.flags }}
        env:
          GOOS: ${{ matrix.GOOS }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```

### Release Action

```
release-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: true
      - shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" &gt;&gt; $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: dist/linux
          key: linux-${{ env.sha_short }}
      - uses: actions/cache@v3
        with:
          path: dist/darwin
          key: darwin-${{ env.sha_short }}
      - uses: goreleaser/goreleaser-action@v4
        if: steps.cache.outputs.cache-hit != 'true' # do not run if cache hit
        with:
          distribution: goreleaser-pro
          version: latest
          args: continue --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
```
